/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.smartstore.service.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.liferay.smartstore.service.model.MobilePhone;
import com.liferay.smartstore.service.model.MobilePhoneModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MobilePhone service. Represents a row in the &quot;mobilephone_MobilePhone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.smartstore.service.model.MobilePhoneModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MobilePhoneImpl}.
 * </p>
 *
 * @author Andre Fabbro
 * @see MobilePhoneImpl
 * @see com.liferay.smartstore.service.model.MobilePhone
 * @see com.liferay.smartstore.service.model.MobilePhoneModel
 * @generated
 */
public class MobilePhoneModelImpl extends BaseModelImpl<MobilePhone>
	implements MobilePhoneModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mobile phone model instance should use the {@link com.liferay.smartstore.service.model.MobilePhone} interface instead.
	 */
	public static final String TABLE_NAME = "mobilephone_MobilePhone";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "name", Types.VARCHAR },
			{ "brand", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "releaseDate", Types.TIMESTAMP },
			{ "price", Types.DOUBLE }
		};
	public static final String TABLE_SQL_CREATE = "create table mobilephone_MobilePhone (id_ LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,brand VARCHAR(75) null,description VARCHAR(75) null,releaseDate DATE null,price DOUBLE)";
	public static final String TABLE_SQL_DROP = "drop table mobilephone_MobilePhone";
	public static final String ORDER_BY_JPQL = " ORDER BY mobilePhone.releaseDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY mobilephone_MobilePhone.releaseDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.smartstore.service.model.MobilePhone"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.smartstore.service.model.MobilePhone"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.smartstore.service.model.MobilePhone"),
			true);
	public static long BRAND_COLUMN_BITMASK = 1L;
	public static long NAME_COLUMN_BITMASK = 2L;
	public static long RELEASEDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.smartstore.service.model.MobilePhone"));

	public MobilePhoneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MobilePhone.class;
	}

	@Override
	public String getModelClassName() {
		return MobilePhone.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("name", getName());
		attributes.put("brand", getBrand());
		attributes.put("description", getDescription());
		attributes.put("releaseDate", getReleaseDate());
		attributes.put("price", getPrice());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String brand = (String)attributes.get("brand");

		if (brand != null) {
			setBrand(brand);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Date releaseDate = (Date)attributes.get("releaseDate");

		if (releaseDate != null) {
			setReleaseDate(releaseDate);
		}

		Double price = (Double)attributes.get("price");

		if (price != null) {
			setPrice(price);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public String getBrand() {
		if (_brand == null) {
			return StringPool.BLANK;
		}
		else {
			return _brand;
		}
	}

	@Override
	public void setBrand(String brand) {
		_columnBitmask |= BRAND_COLUMN_BITMASK;

		if (_originalBrand == null) {
			_originalBrand = _brand;
		}

		_brand = brand;
	}

	public String getOriginalBrand() {
		return GetterUtil.getString(_originalBrand);
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public Date getReleaseDate() {
		return _releaseDate;
	}

	@Override
	public void setReleaseDate(Date releaseDate) {
		_columnBitmask = -1L;

		_releaseDate = releaseDate;
	}

	@Override
	public double getPrice() {
		return _price;
	}

	@Override
	public void setPrice(double price) {
		_price = price;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MobilePhone.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MobilePhone toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MobilePhone)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MobilePhoneImpl mobilePhoneImpl = new MobilePhoneImpl();

		mobilePhoneImpl.setId(getId());
		mobilePhoneImpl.setCompanyId(getCompanyId());
		mobilePhoneImpl.setUserId(getUserId());
		mobilePhoneImpl.setUserName(getUserName());
		mobilePhoneImpl.setCreateDate(getCreateDate());
		mobilePhoneImpl.setModifiedDate(getModifiedDate());
		mobilePhoneImpl.setName(getName());
		mobilePhoneImpl.setBrand(getBrand());
		mobilePhoneImpl.setDescription(getDescription());
		mobilePhoneImpl.setReleaseDate(getReleaseDate());
		mobilePhoneImpl.setPrice(getPrice());

		mobilePhoneImpl.resetOriginalValues();

		return mobilePhoneImpl;
	}

	@Override
	public int compareTo(MobilePhone mobilePhone) {
		int value = 0;

		value = DateUtil.compareTo(getReleaseDate(),
				mobilePhone.getReleaseDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MobilePhone)) {
			return false;
		}

		MobilePhone mobilePhone = (MobilePhone)obj;

		long primaryKey = mobilePhone.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MobilePhoneModelImpl mobilePhoneModelImpl = this;

		mobilePhoneModelImpl._originalName = mobilePhoneModelImpl._name;

		mobilePhoneModelImpl._originalBrand = mobilePhoneModelImpl._brand;

		mobilePhoneModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MobilePhone> toCacheModel() {
		MobilePhoneCacheModel mobilePhoneCacheModel = new MobilePhoneCacheModel();

		mobilePhoneCacheModel.id = getId();

		mobilePhoneCacheModel.companyId = getCompanyId();

		mobilePhoneCacheModel.userId = getUserId();

		mobilePhoneCacheModel.userName = getUserName();

		String userName = mobilePhoneCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mobilePhoneCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mobilePhoneCacheModel.createDate = createDate.getTime();
		}
		else {
			mobilePhoneCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mobilePhoneCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mobilePhoneCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mobilePhoneCacheModel.name = getName();

		String name = mobilePhoneCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			mobilePhoneCacheModel.name = null;
		}

		mobilePhoneCacheModel.brand = getBrand();

		String brand = mobilePhoneCacheModel.brand;

		if ((brand != null) && (brand.length() == 0)) {
			mobilePhoneCacheModel.brand = null;
		}

		mobilePhoneCacheModel.description = getDescription();

		String description = mobilePhoneCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			mobilePhoneCacheModel.description = null;
		}

		Date releaseDate = getReleaseDate();

		if (releaseDate != null) {
			mobilePhoneCacheModel.releaseDate = releaseDate.getTime();
		}
		else {
			mobilePhoneCacheModel.releaseDate = Long.MIN_VALUE;
		}

		mobilePhoneCacheModel.price = getPrice();

		return mobilePhoneCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", brand=");
		sb.append(getBrand());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", releaseDate=");
		sb.append(getReleaseDate());
		sb.append(", price=");
		sb.append(getPrice());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.smartstore.service.model.MobilePhone");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>brand</column-name><column-value><![CDATA[");
		sb.append(getBrand());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>releaseDate</column-name><column-value><![CDATA[");
		sb.append(getReleaseDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>price</column-name><column-value><![CDATA[");
		sb.append(getPrice());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MobilePhone.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MobilePhone.class
		};
	private long _id;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private String _name;
	private String _originalName;
	private String _brand;
	private String _originalBrand;
	private String _description;
	private Date _releaseDate;
	private double _price;
	private long _columnBitmask;
	private MobilePhone _escapedModel;
}